/*  buttons.c - The simplest kernel module.

* Copyright (C) 2013-2022 Xilinx, Inc
* Copyright (c) 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
*
*   This program is free software; you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation; either version 2 of the License, or
*   (at your option) any later version.

*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License along
*   with this program. If not, see <http://www.gnu.org/licenses/>.

*/
#include <linux/cdev.h>
#include <linux/fs.h>
#include <linux/ioctl.h>
#include <linux/uaccess.h>

#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/io.h>
#include <linux/interrupt.h>

#include <linux/of_address.h>
#include <linux/of_device.h>
#include <linux/of_platform.h>
#include <linux/platform_device.h>


/* Standard module information, edit as appropriate */
MODULE_LICENSE("GPL");
MODULE_AUTHOR
    ("Owen O'Connor");
MODULE_DESCRIPTION
    ("buttons - loadable module template generated by petalinux-create -t modules");

#define DRIVER_NAME "buttons"

#define MAX_BUTTONS 16
#define PRESSED_CHAR '1'
#define RELEASED_CHAR '0'

struct btn_local {
	struct cdev cdev;
	dev_t dev_node;
	unsigned long mem_start;
	unsigned long mem_end;
	void __iomem *base_addr;
};


// File operations

// Seels a specific position in the button state file
loff_t btn_llseek(struct file *btn_file, loff_t offset, int whence) {
	    loff_t new_pos = 0;

    switch (whence) {
        case SEEK_SET:
            new_pos = offset;
            break;
        case SEEK_CUR:
            new_pos = btn_file->f_pos + offset;
            break;
        case SEEK_END:
            new_pos = MAX_BUTTONS + offset; // Total number of buttons
            break;
        default:
            return -EINVAL;
    }

    if (new_pos < 0 || new_pos >= MAX_BUTTONS) {
        return -EINVAL;
    }

    btn_file->f_pos = new_pos;
    return new_pos;
}

int btn_open(struct inode *inodep, struct file *filep) {
	struct btn_local *lp = container_of(inodep->i_cdev, struct btn_local, cdev);
	filep->private_data = lp;
	return 0;
}

ssize_t btn_read(struct file *btn_file, char __user *buf, size_t count, loff_t *offset) {
	if (*offset >= MAX_BUTTONS) {
		return 0; // EOF
	}

	if (*offset + count > MAX_BUTTONS) {
		count = MAX_BUTTONS - *offset; // Adjust count to not read past the end
	}

	// Buffer to hold the button states while converting them to characters
	char button_states[MAX_BUTTONS];

	// Get the btn_local data from the file's private data
	struct btn_local *lp = (struct btn_local *)btn_file->private_data;

	// Read the button states from the hardware and convert them to characters
	for (size_t i = 0; i < count; ++i) {
		// Read the state of the button from the hardware
		uint8_t button_state = ioread8(lp->base_addr + (*offset + i));
		button_states[i] = button_state ? PRESSED_CHAR : RELEASED_CHAR;
	}

	// Copy the converted button states to the user buffer
	if (copy_to_user(buf, button_states, count)) {
		return -EFAULT;
	}

	*offset += count;
	return count;
}

static const struct file_operations btn_fops = {
	.owner = THIS_MODULE,
	.llseek = btn_llseek,
	.read = btn_read,
	.open = btn_open
};

static struct class *btn_class;

static int btn_uevent(const struct device *dev, struct kobj_uevent_env *env) {
	add_uevent_var(env, "DEVMODE=%#o", 0666);
	return 0;
}

static int btn_cdev_init(struct cdev *cdev, struct device *dev, dev_t *dev_node) {
	int rc = 0;
    struct device *subdev;

    dev_info(dev, "Initializing character device\n");
    rc = alloc_chrdev_region(dev_node, 0, 1, DRIVER_NAME);

    if (rc) {
        dev_err(dev, "Failed to allocate char device region\n");
        return rc;
    }

    cdev_init(cdev, &btn_fops);
    cdev->owner = THIS_MODULE;
    rc = cdev_add(cdev, *dev_node, 1);

    if (rc) {
        dev_err(dev, "Failed to add char device\n");
        unregister_chrdev_region(*dev_node, 1);
        return rc;
    }

    btn_class = class_create(DRIVER_NAME);

    if (IS_ERR(btn_class)) {
        dev_err(dev, "Failed to create class\n");
        cdev_del(cdev);
        unregister_chrdev_region(*dev_node, 1);
        return PTR_ERR(btn_class);
    }

    btn_class->dev_uevent = btn_uevent;
    subdev = device_create(btn_class, NULL, *dev_node, NULL, DRIVER_NAME);

    if (IS_ERR(subdev)) {
        dev_err(dev, "Failed to create device\n");
        class_destroy(btn_class);
        cdev_del(cdev);
        unregister_chrdev_region(*dev_node, 1);
        return PTR_ERR(subdev);
    }

    return 0; 
}

static void btn_cdev_cleanup(struct cdev *cdev, struct device *dev, dev_t *dev_node) {
    device_destroy(btn_class, *dev_node);
    class_destroy(btn_class);
    cdev_del(cdev);
    unregister_chrdev_region(*dev_node, 1);
}

static int buttons_probe(struct platform_device *pdev) {
	struct resource *r_mem; /* IO mem resources */
	struct device *dev = &pdev->dev;
	struct btn_local *lp = NULL;
	int rc = 0;

	dev_info(dev, "Device Tree Probing\n");

	// Allocate memory for the driver data
    lp = (struct btn_local *) kmalloc(sizeof(struct btn_local), GFP_KERNEL);
    if (!lp) {
        dev_err(dev, "Could not allocate buttons device\n");
        return -ENOMEM;
    }
    dev_set_drvdata(dev, lp);

    /* Get iospace for the device */
    r_mem = platform_get_resource(pdev, IORESOURCE_MEM, 0);
    if (!r_mem) {
        dev_err(dev, "invalid address\n");
        return -ENODEV;
    }
    lp->mem_start = r_mem->start;
    lp->mem_end = r_mem->end;

    if (!request_mem_region(lp->mem_start,
                lp->mem_end - lp->mem_start + 1,
                DRIVER_NAME)) {
        dev_err(dev, "Couldn't lock memory region at %p\n",
            (void *)lp->mem_start);
    
        // release resources and return error code
        kfree(lp);
        dev_set_drvdata(dev, NULL);
        return -EBUSY;
    }

    lp->base_addr = ioremap(lp->mem_start, lp->mem_end - lp->mem_start + 1);
    if (!lp->base_addr) {
        dev_err(dev, "Could not allocate iomem\n");

        // release resources and return error code
        release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
        kfree(lp);
        dev_set_drvdata(dev, NULL);
        return -EIO;
    }

    dev_info(dev, "Initializing character device\n");
    rc = btn_cdev_init(&(lp->cdev), dev, &(lp->dev_node));

    if (rc) {
        dev_err(dev, "Could not initialize character device\n");

        // release resources and return error code
        release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
        kfree(lp);
        dev_set_drvdata(dev, NULL);
        return rc;
    }

	// TODO: I think we need another driver for the xadc to write the initialization values

    dev_info(dev, "buttons at 0x%08x-0x%08x mapped to 0x%08x\n",
        (unsigned int __force)lp->mem_start,
        (unsigned int __force)lp->mem_end,
        (unsigned int __force)lp->base_addr);
    return 0;
}

static void buttons_remove(struct platform_device *pdev){
	struct device *dev = &pdev->dev;
	struct btn_local *lp = dev_get_drvdata(dev);

	btn_cdev_cleanup(&(lp->cdev), dev, &(lp->dev_node));

	iounmap(lp->base_addr);
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	kfree(lp);
	dev_set_drvdata(dev, NULL);
}

#ifdef CONFIG_OF
static struct of_device_id buttons_of_match[] = {
	{ .compatible = "xlnx,buttons-1.0", },
	{ /* end of list */ },
};
MODULE_DEVICE_TABLE(of, buttons_of_match);
#else
# define buttons_of_match
#endif


static struct platform_driver buttons_driver = {
	.driver = {
		.name = DRIVER_NAME,
		.owner = THIS_MODULE,
		.of_match_table	= buttons_of_match,
	},
	.probe		= buttons_probe,
	.remove		= buttons_remove,
};

static int __init buttons_init(void)
{
	printk("buttons: Initializing driver\n");

	return platform_driver_register(&buttons_driver);
}


static void __exit buttons_exit(void)
{
	platform_driver_unregister(&buttons_driver);
	printk("buttons: Exiting driver\n");
}

module_init(buttons_init);
module_exit(buttons_exit);
