/*  xadc-init.c - The simplest kernel module.

* Copyright (C) 2013-2022 Xilinx, Inc
* Copyright (c) 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
*
*   This program is free software; you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation; either version 2 of the License, or
*   (at your option) any later version.

*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License along
*   with this program. If not, see <http://www.gnu.org/licenses/>.

*/
#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/io.h>
#include <linux/interrupt.h>

#include <linux/of_address.h>
#include <linux/of_device.h>
#include <linux/of_platform.h>
#include <linux/platform_device.h>

/* Standard module information, edit as appropriate */
MODULE_LICENSE("GPL");
MODULE_AUTHOR
    ("Xilinx Inc.");
MODULE_DESCRIPTION
    ("xadc-init - loadable module template generated by petalinux-create -t modules");

#define DRIVER_NAME "xadc-init"

#define XADC_CONFIG_OFFSET 0x300
#define XADC_CONFIG_NUM_REGS 16

const uint32_t XADC_CONFIG_REGS[16] = {
	0x00000011, 0x00002faf, 0x00002000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000002, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000
};

struct xadc_local {
	unsigned long mem_start;
	unsigned long mem_end;
	void __iomem *base_addr;
};


static int xadc_probe(struct platform_device *pdev) {
	struct resource *r_mem; /* IO mem resources */
    struct device *dev = &pdev->dev;
    struct xadc_local *lp = NULL;
    int rc = 0;

    dev_info(dev, "Device Tree Probing\n");
	
	// Allocate memory for the driver data
    lp = (struct xadc_local *) kmalloc(sizeof(struct xadc_local), GFP_KERNEL);
    if (!lp) {
        dev_err(dev, "Could not allocate xadc device\n");
        return -ENOMEM;
    }
    dev_set_drvdata(dev, lp);

    /* Get iospace for the device */
    r_mem = platform_get_resource(pdev, IORESOURCE_MEM, 0);
    if (!r_mem) {
        dev_err(dev, "invalid address\n");
        return -ENODEV;
    }
    lp->mem_start = r_mem->start;
    lp->mem_end = r_mem->end;

    if (!request_mem_region(lp->mem_start,
                lp->mem_end - lp->mem_start + 1,
                DRIVER_NAME)) {
        dev_err(dev, "Couldn't lock memory region at %p\n",
            (void *)lp->mem_start);
    
        // release resources and return error code
        kfree(lp);
        dev_set_drvdata(dev, NULL);
        return -EBUSY;
    }

    lp->base_addr = ioremap(lp->mem_start, lp->mem_end - lp->mem_start + 1);
    if (!lp->base_addr) {
        dev_err(dev, "Could not allocate iomem\n");

        // release resources and return error code
        release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
        kfree(lp);
        dev_set_drvdata(dev, NULL);
        return -EIO;
    }

    // This is a bit scuffed, but it's okay
    memcpy((void *)(lp->base_addr + XADC_CONFIG_OFFSET), (void *)XADC_CONFIG_REGS, XADC_CONFIG_NUM_REGS * sizeof(uint32_t));

    dev_info(dev, "xadc at 0x%08x-0x%08x mapped to 0x%08x\n",
        (unsigned int __force)lp->mem_start,
        (unsigned int __force)lp->mem_end,
        (unsigned int __force)lp->base_addr);
    return 0;
}

static void xadc_remove(struct platform_device *pdev)
{
	struct device *dev = &pdev->dev;
	struct xadc_local *lp = dev_get_drvdata(dev);
	iounmap(lp->base_addr);
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	kfree(lp);
	dev_set_drvdata(dev, NULL);
}

#ifdef CONFIG_OF
static struct of_device_id xadc_of_match[] = {
	{ .compatible = "xlnx,xadc-wiz-3.3", },
	{ /* end of list */ },
};
MODULE_DEVICE_TABLE(of, xadc_of_match);
#else
# define xadc_of_match
#endif


static struct platform_driver xadc_driver = {
	.driver = {
		.name = DRIVER_NAME,
		.owner = THIS_MODULE,
		.of_match_table	= xadc_of_match,
	},
	.probe		= xadc_probe,
	.remove		= xadc_remove,
};

static int __init xadc_init(void)
{
	printk("xadc-init: Initializing driver\n");

	return platform_driver_register(&xadc_driver);
}


static void __exit xadc_exit(void)
{
	platform_driver_unregister(&xadc_driver);
	printk("xadc-init: Exiting driver\n");
}

module_init(xadc_init);
module_exit(xadc_exit);
