/*  lcd.c - The simplest kernel module.

* Copyright (C) 2013-2022 Xilinx, Inc
* Copyright (c) 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
*
*   This program is free software; you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation; either version 2 of the License, or
*   (at your option) any later version.

*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License along
*   with this program. If not, see <http://www.gnu.org/licenses/>.

*/
#include <linux/cdev.h>
#include <linux/fs.h>
#include <linux/ioctl.h>
#include <linux/uaccess.h>

#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/io.h>
#include <linux/interrupt.h>

#include <linux/of_address.h>
#include <linux/of_device.h>
#include <linux/of_platform.h>
#include <linux/platform_device.h>

/* Standard module information, edit as appropriate */
MODULE_LICENSE("GPL");
MODULE_AUTHOR
    ("Owen O'Connor");
MODULE_DESCRIPTION
    ("lcd - loadable module template generated by petalinux-create -t modules");

#define DRIVER_NAME "lcd"

#define NUM_ROWS 2
#define NUM_COLS 16


struct lcd_local {
    struct cdev cdev;
    dev_t dev_node;
    unsigned long mem_start;
    unsigned long mem_end;
    void __iomem *base_addr;
};


// initialize file operations

// Seeks a specific position in the LCD character buffer
loff_t lcd_llseek(struct file *lcd_file, loff_t offset, int whence) {
    loff_t new_pos = 0;

    switch (whence) {
        case SEEK_SET:
            new_pos = offset;
            break;
        case SEEK_CUR:
            new_pos = lcd_file->f_pos + offset;
            break;
        case SEEK_END:
            new_pos = (NUM_ROWS * NUM_COLS) + offset; // Total number of characters
            break;
        default:
            return -EINVAL;
    }

    if (new_pos < 0 || new_pos >= (NUM_ROWS * NUM_COLS)) {
        return -EINVAL;
    }

    lcd_file->f_pos = new_pos;
    return new_pos;
}

int lcd_open(struct inode *inode, struct file *lcd_file) {
    // Save the lcd_local data to the file's private data for later use
    struct lcd_local *lp = container_of(inode->i_cdev, struct lcd_local, cdev);
    lcd_file->private_data = lp;
    return 0;
}

ssize_t lcd_read(struct file *lcd_file, char __user *buf, size_t count, loff_t *offset) {
    if (*offset >= (NUM_ROWS * NUM_COLS)) {
        return 0; // EOF
    }

    if (*offset + count > (NUM_ROWS * NUM_COLS)) {
        count = (NUM_ROWS * NUM_COLS) - *offset; // Adjust count to available data
    }

    // Get the lcd_local data from the file's private data
    struct lcd_local *lp = (struct lcd_local *)lcd_file->private_data;

    if (copy_to_user(buf, ((char *)(lp->base_addr)) + *offset, count)) {
        return -EFAULT;
    }

    *offset += count;
    return count;    
}

// Writing will be a little bit weird. When we hit the end of the LCD buffer, we want to automatically wrap around to the beginning of the buffer
static ssize_t lcd_write(struct file *lcd_file, const char __user *buf, size_t count, loff_t *offset) {
    loff_t pos = *offset;

    // Get the lcd_local data from the file's private data
    struct lcd_local *lp = (struct lcd_local *)lcd_file->private_data;

    // TODO: you could probably make this more efficient by working in chunks or skipping the data in the middle of very large writes
    for (size_t i = 0; i < count; ++i) {
        char c;

        if (copy_from_user(&c, buf + i, 1)) {
            return -EFAULT;
        }

        // Write the character to the LCD buffer
        ((char *)(lp->base_addr))[pos] = c;

        // Move to the next position, wrapping around if necessary
        pos = (pos + 1) % (NUM_ROWS * NUM_COLS);
    }

    *offset = pos;
    return count;
}

static const struct file_operations lcd_fops = {
    .owner = THIS_MODULE,
    .llseek = lcd_llseek,
    .read = lcd_read,
    .write = lcd_write,
    .open = lcd_open
};

static struct class *lcd_class;

static int lcd_uevent(const struct device *dev, struct kobj_uevent_env *env) {
    add_uevent_var(env, "DEVMODE=%#o", 0666);
    return 0;
}

static int lcd_cdev_init(struct cdev *cdev, struct device *dev, dev_t *dev_node) {
    int rc = 0;
    struct device *subdev;

    dev_info(dev, "Initializing character device\n");
    rc = alloc_chrdev_region(dev_node, 0, 1, DRIVER_NAME);

    if (rc) {
        dev_err(dev, "Failed to allocate char device region\n");
        return rc;
    }

    cdev_init(cdev, &lcd_fops);
    cdev->owner = THIS_MODULE;
    rc = cdev_add(cdev, *dev_node, 1);

    if (rc) {
        dev_err(dev, "Failed to add char device\n");
        unregister_chrdev_region(*dev_node, 1);
        return rc;
    }

    lcd_class = class_create(DRIVER_NAME);

    if (IS_ERR(lcd_class)) {
        dev_err(dev, "Failed to create class\n");
        cdev_del(cdev);
        unregister_chrdev_region(*dev_node, 1);
        return PTR_ERR(lcd_class);
    }

    lcd_class->dev_uevent = lcd_uevent;
    subdev = device_create(lcd_class, NULL, *dev_node, NULL, DRIVER_NAME);

    if (IS_ERR(subdev)) {
        dev_err(dev, "Failed to create device\n");
        class_destroy(lcd_class);
        cdev_del(cdev);
        unregister_chrdev_region(*dev_node, 1);
        return PTR_ERR(subdev);
    }

    return 0;    
}

static void lcd_cdev_cleanup(struct cdev *cdev, struct device *dev, dev_t *dev_node) {
    device_destroy(lcd_class, *dev_node);
    class_destroy(lcd_class);
    cdev_del(cdev);
    unregister_chrdev_region(*dev_node, 1);
}


static int lcd_probe(struct platform_device *pdev) {
    struct resource *r_mem; /* IO mem resources */
    struct device *dev = &pdev->dev;
    struct lcd_local *lp = NULL;
    int rc = 0;

    dev_info(dev, "Device Tree Probing\n");

    // Allocate memory for the driver data
    lp = (struct lcd_local *) kmalloc(sizeof(struct lcd_local), GFP_KERNEL);
    if (!lp) {
        dev_err(dev, "Cound not allocate lcd device\n");
        return -ENOMEM;
    }
    dev_set_drvdata(dev, lp);

    /* Get iospace for the device */
    r_mem = platform_get_resource(pdev, IORESOURCE_MEM, 0);
    if (!r_mem) {
        dev_err(dev, "invalid address\n");
        return -ENODEV;
    }
    lp->mem_start = r_mem->start;
    lp->mem_end = r_mem->end;

    if (!request_mem_region(lp->mem_start,
                lp->mem_end - lp->mem_start + 1,
                DRIVER_NAME)) {
        dev_err(dev, "Couldn't lock memory region at %p\n",
            (void *)lp->mem_start);
    
        // release resources and return error code
        kfree(lp);
        dev_set_drvdata(dev, NULL);
        return -EBUSY;
    }

    lp->base_addr = ioremap(lp->mem_start, lp->mem_end - lp->mem_start + 1);
    if (!lp->base_addr) {
        dev_err(dev, "lcd: Could not allocate iomem\n");

        // release resources and return error code
        release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
        kfree(lp);
        dev_set_drvdata(dev, NULL);
        return -EIO;
    }

    dev_info(dev, "Initializing character device\n");
    rc = lcd_cdev_init(&(lp->cdev), dev, &(lp->dev_node));

    if (rc) {
        dev_err(dev, "lcd: Could not initialize character device\n");

        // release resources and return error code
        release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
        kfree(lp);
        dev_set_drvdata(dev, NULL);
        return rc;
    }

    ((char *)(lp->base_addr))[0] = 't';
    ((char *)(lp->base_addr))[1] = 'e';
    ((char *)(lp->base_addr))[2] = 's';
    ((char *)(lp->base_addr))[3] = 't';

    // This is a bit scuffed, but it's okay
    memcpy((void *)(lp->base_addr), (void *)("LCD driver init "), 16);
    memcpy((void *)(lp->base_addr) + 16, (void *)("  complete!     "), 16);

    dev_info(dev, "lcd at 0x%08x-0x%08x mapped to 0x%08x\n",
        (unsigned int __force)lp->mem_start,
        (unsigned int __force)lp->mem_end,
        (unsigned int __force)lp->base_addr);
    return 0;
}

static void lcd_remove(struct platform_device *pdev) {
    struct device *dev = &pdev->dev;
    struct lcd_local *lp = dev_get_drvdata(dev);

    lcd_cdev_cleanup(&(lp->cdev), dev, &(lp->dev_node));

    iounmap(lp->base_addr);
    release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
    kfree(lp);
    dev_set_drvdata(dev, NULL);
}

#ifdef CONFIG_OF
static struct of_device_id lcd_of_match[] = {
    { .compatible = "xlnx,lcd-1.0", },
    { /* end of list */ },
};
MODULE_DEVICE_TABLE(of, lcd_of_match);
#else
# define lcd_of_match
#endif

static struct platform_driver lcd_driver = {
    .driver = {
        .name = DRIVER_NAME,
        .owner = THIS_MODULE,
        .of_match_table	= lcd_of_match,
    },
    .probe		= lcd_probe,
    .remove		= lcd_remove,
};


static int __init lcd_init(void) {
    printk("lcd: Initializing driver\n");

    return platform_driver_register(&lcd_driver);
}


static void __exit lcd_exit(void) {
    platform_driver_unregister(&lcd_driver);
    printk("lcd: Exiting driver\n");
}

module_init(lcd_init);
module_exit(lcd_exit);
